Repository OpenSecuritySummit/oss2018, pull requests merged in 2018-05, with the labels that each got.

#342 Home page update
  layouts/partials/features.html
  layouts/partials/sponsors.html
  static/css/custom.css
  static/img/sponsors/owasp.png
Labels: needs-review

#372 fix responsive issue with container
  static/css/custom.css
Labels: needs-review

#735 Update writing-security-tests-to-confirm-vulnerabilities-and-fixes.md
  content/tracks/DevSecOps/user-sessions/writing-security-tests-to-confirm-vulnerabilities-and-fixes.md
Labels: broken syntax

#730 Added sessions to tashnorris participant page.
  content/participant/capital-one/tash-norris.md
Labels: session name changed
